##
 # Copyright (c) Jaime Elso de Blas (https://jaimeelso.com)
 # Follow me on twitter: @jaimeelso
 # Check out my Github: https://github.com/jaimeelso
 # This code is licensed under the MIT license.
 # Created on: 02/28/2023
 #
 # Version: 1.0
 # Description: This CloudFormation template gathers all necessary resources and their configurations to 
 # deploy an API Gateway that handles the backend calls from my website.
##

AWSTemplateFormatVersion: 2010-09-09
Description: API Gateway that handles the backend calls from my website jaimeelso.com

Resources:
  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: jaimeelso
      Description: API that manages all the backends on my website
      ProtocolType: HTTP
      RouteSelectionExpression: $request.method $request.path
      DisableExecuteApiEndpoint: true
      CorsConfiguration:
        AllowCredentials: false
        AllowHeaders:
          - content-type
        AllowMethods:
          - POST
          - OPTIONS
        AllowOrigins:
          - https://jaimeelso.com
        MaxAge: 0
      Tags:
        Project: MyWebsite
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref Api
      StageName: default
      Description: Default stage
      AutoDeploy: true
      DefaultRouteSettings:
        DetailedMetricsEnabled: false
        ThrottlingBurstLimit: 1
        ThrottlingRateLimit: 1.0
      Tags:
        Project: MyWebsite

Outputs:
  ApiId:
    Value: !Ref Api
    Description: The ID of the AWS API Gateway that manages the backend on the web jaimeelso.com.
    Export:
      Name: !Sub "${AWS::StackName}-ApiId"
